language: ruby
script: rake ci 
rvm:
  - ruby-head
#  - 2.2.0 # has a bug affecting rdf gem:  https://github.com/ruby-rdf/rdf/issues/167
  - 2.1.5
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    - ndushay@stanford.edu
    - cabeer@stanford.edu
    - wmene@stanford.edu
