development:
  ldp_url: yer_ldp_store_url_here
  solr_url: yer_triannon_solr_url_here
  triannon_base_url: http://your.triannon-server.com/annotations/
  max_solr_retries: 5
  base_sleep_seconds: 1
  max_sleep_seconds: 5
test: &test
  ldp_url: yer_ldp_url_here
  solr_url: yer_triannon_solr_url_here
  triannon_base_url: http://your.triannon-server.com/annotations/
production:
  ldp_url: yer_ldp_url_here
  solr_url: yer_triannon_solr_url_here
  triannon_base_url: http://your.triannon-server.com/annotations/
